// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    return robot.hear(/ぬるぽ/, function(msg) {
      return msg.send('■━⊂(　・∀・) 彡 ｶﾞｯ☆`Д´)ﾉ`');
    });
  };

}).call(this);
